### ISSUE TITLE
小程序中自定义Element 使用报错

### ISSUE THREAD

**Issue by JasonMiss** [dntzhang/cax#10]
import cax from './index'

export default class poker extends cax.Group {
  constructor() {
    super()
    const bitmap = new cax.Bitmap('../../image/user_avatar_test.png')
    bitmap.scaleX = bitmap.scaleY = 0.5
    this.add(this.bitmap)
  }
}

error:
Cannot set property 'parent' of undefined;at "pages/live/live" page lifeCycleMethod onLoad function
TypeError: Cannot set property 'parent' of undefined
    at poker.add (http://127.0.0.1:35894/appservice/components/cax/index.js:298:35)
    at new poker (http://127.0.0.1:35894/appservice/components/cax/poker.js:29:11)
    at r.onLoad (http://127.0.0.1:35894/appservice/pages/live/live.js:67:17)
    at r.<anonymous> (

**Comment by dntzhang** [comment]
this.add(this.bitmap) 改成  this.add(bitmap)
